config:
  credentials:
  - id: orviz-github-basico
    password_var: JP_DOCKERPASS
    type: username_password
    username_var: JP_DOCKERUSER
environment:
  JPL_DOCKERSERVER: https://hub.docker.com/
sqa_criteria:
  qc_doc:
    repos:
      test_sqaaas-api-spec:
        commands:
        - npm --prefix /sqaaas-api-spec install
        - npm --prefix /sqaaas-api-spec run build
        container: node
