config:
  credentials:
  - id: orviz-github-basico
    password_var: GIT_PASS
    type: username_password
    username_var: GIT_USER
environment:
  JPL_DOCKERSERVER: https://hub.docker.com/
sqa_criteria:
  qc_style:
    repos:
      test_sqaaas-api-spec:
        commands:
        - npm --prefix /sqaaas-api-spec install
        - npm --prefix /sqaaas-api-spec test
        container: node
